import { afterEach, describe, expect, it } from "bun:test";
import {
  BROWSER_BOOT_URL,
  BROWSER_CDP_PORT,
  BROWSER_USER_DATA_DIR,
  buildWindowsCdpPortProxyAddArgs,
  buildWindowsCdpPortProxyDeleteArgs,
  buildElevatedProcessArgs,
  buildElevatedProcessCommand,
  buildChromeStartArgs,
  buildChromeStartCommand,
  buildConfiguredBrowserCdpUrl,
  buildRemoteCdpUrl,
  buildWindowsElevationCheckArgs,
  normalizeBrowserCdpPort,
  parseFirstNameserver,
  resolveBrowserCdpPort,
  resolveChromeExePath,
} from "../../../app/server/tasks/browser";

const originalChromePathEnv = process.env.CLAWOS_CHROME_EXE_PATH;

afterEach(() => {
  if (originalChromePathEnv === undefined) {
    delete process.env.CLAWOS_CHROME_EXE_PATH;
    return;
  }
  process.env.CLAWOS_CHROME_EXE_PATH = originalChromePathEnv;
});

describe("browser cdp helpers", () => {
  it("uses env override chrome path when provided", () => {
    process.env.CLAWOS_CHROME_EXE_PATH = "D:\\tools\\chrome\\chrome.exe";
    expect(resolveChromeExePath()).toBe("D:\\tools\\chrome\\chrome.exe");
  });

  it("builds powershell start command and args safely", () => {
    const exePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome's.exe";
    const command = buildChromeStartCommand(exePath, "C:\\Program Files\\Google\\Chrome\\Application", 9333);
    const args = buildChromeStartArgs(exePath, "C:\\Program Files\\Google\\Chrome\\Application", 9333);

    expect(command).toContain("Start-Process -FilePath 'C:\\Program Files\\Google\\Chrome\\Application\\chrome''s.exe'");
    expect(command).toContain("'--remote-debugging-port=9333'");
    expect(command).toContain(`'--user-data-dir=${BROWSER_USER_DATA_DIR}'`);
    expect(command).toContain(`'${BROWSER_BOOT_URL}'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("builds powershell elevation helpers safely", () => {
    const exePath = "C:\\Windows\\System32\\netsh.exe";
    const command = buildElevatedProcessCommand(exePath, ["advfirewall", "show", "allprofiles"]);
    const args = buildElevatedProcessArgs(exePath, ["advfirewall", "show", "allprofiles"]);

    expect(command).toContain("Start-Process -FilePath 'C:\\Windows\\System32\\netsh.exe'");
    expect(command).toContain("-Verb RunAs");
    expect(command).toContain(`-ArgumentList 'advfirewall show allprofiles'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("builds netsh portproxy commands for WSL access", () => {
    expect(buildWindowsCdpPortProxyDeleteArgs(9333, "172.31.64.1")).toEqual([
      "netsh.exe",
      "interface",
      "portproxy",
      "delete",
      "v4tov4",
      "listenport=9333",
      "listenaddress=172.31.64.1",
    ]);
    expect(buildWindowsCdpPortProxyAddArgs(9333, "172.31.64.1")).toEqual([
      "netsh.exe",
      "interface",
      "portproxy",
      "add",
      "v4tov4",
      "listenport=9333",
      "listenaddress=172.31.64.1",
      "connectport=9333",
      "connectaddress=127.0.0.1",
    ]);
  });

  it("builds admin check powershell args", () => {
    const args = buildWindowsElevationCheckArgs();
    expect(args.slice(0, 6)).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
    ]);
    expect(args[6]).toContain("WindowsBuiltInRole");
  });

  it("parses first nameserver from resolv.conf", () => {
    const nameserver = parseFirstNameserver(`
# generated by WSL
nameserver 172.31.64.1
nameserver 8.8.8.8
`);
    expect(nameserver).toBe("172.31.64.1");
  });

  it("builds remote cdp url with WSL nameserver", () => {
    const remote = buildRemoteCdpUrl("ws://127.0.0.1:9333/devtools/browser/abc", "172.31.64.1", 9333);
    expect(remote).toBe("http://172.31.64.1:9333/");
  });

  it("updates configured cdp url without using browser.cdpPort", () => {
    expect(buildConfiguredBrowserCdpUrl("http://172.31.64.1:9222/", 9224)).toBe("http://172.31.64.1:9224/");
    expect(buildConfiguredBrowserCdpUrl("ws://127.0.0.1:9222/devtools/browser/abc", 9224)).toBe("http://127.0.0.1:9224/");
    expect(buildConfiguredBrowserCdpUrl(undefined, 9224)).toBe("http://127.0.0.1:9224/");
  });

  it("normalizes configured browser cdp ports safely", () => {
    expect(normalizeBrowserCdpPort("9333")).toBe(9333);
    expect(normalizeBrowserCdpPort(0)).toBe(BROWSER_CDP_PORT);
    expect(normalizeBrowserCdpPort("abc")).toBe(BROWSER_CDP_PORT);
  });

  it("resolves browser cdp port from cdpUrl", () => {
    expect(resolveBrowserCdpPort({ cdpPort: 9333 })).toBe(BROWSER_CDP_PORT);
    expect(resolveBrowserCdpPort({ cdpUrl: "http://172.31.64.1:18801/" })).toBe(18801);
    expect(resolveBrowserCdpPort({})).toBe(BROWSER_CDP_PORT);
  });
});
