import { afterEach, describe, expect, it } from "bun:test";
import {
  BROWSER_BOOT_URL,
  BROWSER_CDP_BIND_ADDRESS,
  BROWSER_CDP_PORT,
  BROWSER_USER_DATA_DIR,
  buildWindowsCdpPortProxyAddArgs,
  buildWindowsCdpPortProxyDeleteArgs,
  buildFreshChromeUserDataDir,
  buildElevatedProcessArgs,
  buildElevatedProcessCommand,
  buildChromeStartArgs,
  buildChromeStartCommand,
  buildRemoteCdpUrl,
  buildWindowsElevationCheckArgs,
  parseFirstNameserver,
  resolveChromeExePath,
} from "../../app/src/tasks/browser";

const originalChromePathEnv = process.env.CLAWOS_CHROME_EXE_PATH;

afterEach(() => {
  if (originalChromePathEnv === undefined) {
    delete process.env.CLAWOS_CHROME_EXE_PATH;
    return;
  }
  process.env.CLAWOS_CHROME_EXE_PATH = originalChromePathEnv;
});

describe("browser cdp helpers", () => {
  it("uses env override chrome path when provided", () => {
    process.env.CLAWOS_CHROME_EXE_PATH = "D:\\tools\\chrome\\chrome.exe";
    expect(resolveChromeExePath()).toBe("D:\\tools\\chrome\\chrome.exe");
  });

  it("builds powershell start command and args safely", () => {
    const exePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome's.exe";
    const command = buildChromeStartCommand(exePath, "C:\\Program Files\\Google\\Chrome\\Application");
    const args = buildChromeStartArgs(exePath, "C:\\Program Files\\Google\\Chrome\\Application");

    expect(command).toContain("Start-Process -FilePath 'C:\\Program Files\\Google\\Chrome\\Application\\chrome''s.exe'");
    expect(command).toContain(`'--remote-debugging-address=${BROWSER_CDP_BIND_ADDRESS}'`);
    expect(command).toContain(`'--remote-debugging-port=${BROWSER_CDP_PORT}'`);
    expect(command).toContain(`'--user-data-dir=${BROWSER_USER_DATA_DIR}'`);
    expect(command).toContain(`'${BROWSER_BOOT_URL}'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("builds powershell start command with a fresh chrome profile", () => {
    const freshDir = buildFreshChromeUserDataDir("C:\\chrome-openclaw", 42);
    const command = buildChromeStartCommand("C:\\Chrome\\chrome.exe", "C:\\Chrome", { userDataDir: freshDir });

    expect(freshDir).toBe("C:\\chrome-openclaw-cdp-42");
    expect(command).toContain(`'--user-data-dir=${freshDir}'`);
  });

  it("builds powershell elevation helpers safely", () => {
    const exePath = "C:\\Windows\\System32\\netsh.exe";
    const command = buildElevatedProcessCommand(exePath, ["advfirewall", "show", "allprofiles"]);
    const args = buildElevatedProcessArgs(exePath, ["advfirewall", "show", "allprofiles"]);

    expect(command).toContain("Start-Process -FilePath 'C:\\Windows\\System32\\netsh.exe'");
    expect(command).toContain("-Verb RunAs");
    expect(command).toContain(`-ArgumentList 'advfirewall show allprofiles'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("builds netsh portproxy commands for WSL access", () => {
    expect(buildWindowsCdpPortProxyDeleteArgs()).toEqual([
      "netsh.exe",
      "interface",
      "portproxy",
      "delete",
      "v4tov4",
      `listenport=${BROWSER_CDP_PORT}`,
      "listenaddress=0.0.0.0",
    ]);
    expect(buildWindowsCdpPortProxyAddArgs()).toEqual([
      "netsh.exe",
      "interface",
      "portproxy",
      "add",
      "v4tov4",
      `listenport=${BROWSER_CDP_PORT}`,
      "listenaddress=0.0.0.0",
      `connectport=${BROWSER_CDP_PORT}`,
      "connectaddress=127.0.0.1",
    ]);
  });

  it("builds admin check powershell args", () => {
    const args = buildWindowsElevationCheckArgs();
    expect(args.slice(0, 6)).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
    ]);
    expect(args[6]).toContain("WindowsBuiltInRole");
  });

  it("parses first nameserver from resolv.conf", () => {
    const nameserver = parseFirstNameserver(`
# generated by WSL
nameserver 172.31.64.1
nameserver 8.8.8.8
`);
    expect(nameserver).toBe("172.31.64.1");
  });

  it("builds remote cdp url with WSL nameserver", () => {
    const remote = buildRemoteCdpUrl(`ws://127.0.0.1:${BROWSER_CDP_PORT}/devtools/browser/abc`, "172.31.64.1");
    expect(remote).toBe(`ws://172.31.64.1:${BROWSER_CDP_PORT}/devtools/browser/abc`);
  });

});
