import { afterEach, describe, expect, it } from "bun:test";
import {
  BROWSER_BOOT_URL,
  BROWSER_CDP_PORT,
  BROWSER_REMOTE_CDP_PORT,
  BROWSER_USER_DATA_DIR,
  buildElevatedProcessArgs,
  buildElevatedProcessCommand,
  buildChromeStartArgs,
  buildChromeStartCommand,
  buildWindowsElevationCheckArgs,
  buildRemoteCdpUrl,
  parseFirstNameserver,
  resolveChromeExePath,
} from "../../src/tasks/browser";

const originalChromePathEnv = process.env.CLAWOS_CHROME_EXE_PATH;

afterEach(() => {
  if (originalChromePathEnv === undefined) {
    delete process.env.CLAWOS_CHROME_EXE_PATH;
    return;
  }
  process.env.CLAWOS_CHROME_EXE_PATH = originalChromePathEnv;
});

describe("browser cdp helpers", () => {
  it("uses env override chrome path when provided", () => {
    process.env.CLAWOS_CHROME_EXE_PATH = "D:\\tools\\chrome\\chrome.exe";
    expect(resolveChromeExePath()).toBe("D:\\tools\\chrome\\chrome.exe");
  });

  it("builds powershell start command and args safely", () => {
    const exePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome's.exe";
    const command = buildChromeStartCommand(exePath, "C:\\Program Files\\Google\\Chrome\\Application");
    const args = buildChromeStartArgs(exePath, "C:\\Program Files\\Google\\Chrome\\Application");

    expect(command).toContain("Start-Process -FilePath 'C:\\Program Files\\Google\\Chrome\\Application\\chrome''s.exe'");
    expect(command).toContain(`'--remote-debugging-port=${BROWSER_CDP_PORT}'`);
    expect(command).toContain(`'--user-data-dir=${BROWSER_USER_DATA_DIR}'`);
    expect(command).toContain(`'${BROWSER_BOOT_URL}'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("builds powershell elevation helpers safely", () => {
    const exePath = "C:\\Windows\\System32\\netsh.exe";
    const command = buildElevatedProcessCommand(exePath, ["advfirewall", "firewall", "add", "rule", "name=ClawOS CDP 9223"]);
    const args = buildElevatedProcessArgs(exePath, ["advfirewall", "firewall", "add", "rule", "name=ClawOS CDP 9223"]);

    expect(command).toContain("Start-Process -FilePath 'C:\\Windows\\System32\\netsh.exe'");
    expect(command).toContain("-Verb RunAs");
    expect(command).toContain(`-ArgumentList 'advfirewall firewall add rule "name=ClawOS CDP 9223"'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("builds admin check powershell args", () => {
    const args = buildWindowsElevationCheckArgs();
    expect(args.slice(0, 6)).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
    ]);
    expect(args[6]).toContain("WindowsBuiltInRole");
  });

  it("parses first nameserver from resolv.conf", () => {
    const nameserver = parseFirstNameserver(`
# generated by WSL
nameserver 172.31.64.1
nameserver 8.8.8.8
`);
    expect(nameserver).toBe("172.31.64.1");
  });

  it("builds remote cdp url with remote proxy port", () => {
    const remote = buildRemoteCdpUrl("ws://127.0.0.1:9222/devtools/browser/abc", "172.28.240.1");
    expect(remote).toBe(`ws://172.28.240.1:${BROWSER_REMOTE_CDP_PORT}/devtools/browser/abc`);
  });
});
