import { afterEach, describe, expect, it } from "bun:test";
import {
  BROWSER_BOOT_URL,
  BROWSER_CDP_PORT,
  BROWSER_USER_DATA_DIR,
  buildChromeStartArgs,
  buildChromeStartCommand,
  buildRemoteCdpUrl,
  parseFirstNameserver,
  resolveChromeExePath,
} from "../../src/tasks/browser";

const originalChromePathEnv = process.env.CLAWOS_CHROME_EXE_PATH;

afterEach(() => {
  if (originalChromePathEnv === undefined) {
    delete process.env.CLAWOS_CHROME_EXE_PATH;
    return;
  }
  process.env.CLAWOS_CHROME_EXE_PATH = originalChromePathEnv;
});

describe("browser cdp helpers", () => {
  it("uses env override chrome path when provided", () => {
    process.env.CLAWOS_CHROME_EXE_PATH = "D:\\tools\\chrome\\chrome.exe";
    expect(resolveChromeExePath()).toBe("D:\\tools\\chrome\\chrome.exe");
  });

  it("builds powershell start command and args safely", () => {
    const exePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome's.exe";
    const command = buildChromeStartCommand(exePath, "C:\\Program Files\\Google\\Chrome\\Application");
    const args = buildChromeStartArgs(exePath, "C:\\Program Files\\Google\\Chrome\\Application");

    expect(command).toContain("Start-Process -FilePath 'C:\\Program Files\\Google\\Chrome\\Application\\chrome''s.exe'");
    expect(command).toContain(`'--remote-debugging-port=${BROWSER_CDP_PORT}'`);
    expect(command).toContain(`'--user-data-dir=${BROWSER_USER_DATA_DIR}'`);
    expect(command).toContain(`'${BROWSER_BOOT_URL}'`);
    expect(args).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      command,
    ]);
  });

  it("parses first nameserver from resolv.conf", () => {
    const nameserver = parseFirstNameserver(`
# generated by WSL
nameserver 172.31.64.1
nameserver 8.8.8.8
`);
    expect(nameserver).toBe("172.31.64.1");
  });

  it("builds remote cdp url with unified port 9222", () => {
    const remote = buildRemoteCdpUrl("ws://127.0.0.1:9222/devtools/browser/abc", "172.28.240.1");
    expect(remote).toBe(`ws://172.28.240.1:${BROWSER_CDP_PORT}/devtools/browser/abc`);
  });
});
