import { describe, expect, it } from "bun:test";
import { buildRemoteCdpUrl, parseAllNameservers, parseDefaultGateway, parseFirstNameserver } from "../../../app/server/tasks/browser";

describe("browser connectivity helpers", () => {
  it("parses first nameserver from resolv.conf", () => {
    const nameserver = parseFirstNameserver(`
# generated by WSL
nameserver 172.31.64.1
nameserver 8.8.8.8
`);
    expect(nameserver).toBe("172.31.64.1");
  });

  it("parses all nameservers from resolv.conf", () => {
    const nameservers = parseAllNameservers(`
nameserver 172.31.64.1
nameserver 8.8.8.8
`);
    expect(nameservers).toEqual(["172.31.64.1", "8.8.8.8"]);
  });

  it("parses default gateway from ip route output", () => {
    const gateway = parseDefaultGateway("default via 172.31.64.1 dev eth0 proto kernel\n");
    expect(gateway).toBe("172.31.64.1");
  });

  it("builds remote cdp url with discovered host", () => {
    const remote = buildRemoteCdpUrl("ws://127.0.0.1:9222/devtools/browser/abc", "172.31.64.1");
    expect(remote).toBe("ws://172.31.64.1:9222/devtools/browser/abc");
  });
});
